# 0515: M+ table (w = log(1+x)), S = 2^256, rows j < 64, base length 191.
from gen_tab import *
from fractions import Fraction as Fr
S=2**256
lo=Fr(6931471805599453094172321214581765680755001343602552541206800094933936219696947156058633269964186875,10**100)
hi=lo+Fr(1,10**100)
mu0=ball_of_bounds(S,2*lo-2,2*hi-2)
base=[mu0]+[ratBall(S,2 if l%2==1 else -2,l*(l+1)) for l in range(1,191)]
t=rows(base,64)
print('lens',len(t[0]),len(t[-1]),'max radius bits',max(r for row in t for c,r in row).bit_length())
# numeric check against mpmath
import mpmath as mp
mp.mp.dps=80
for (j,l) in [(5,7),(63,127),(40,90)]:
  q=mp.quad(lambda u: mp.log(1+u)*mp.legendre(j,u)*mp.legendre(l,u),mp.linspace(-1,1,9))
  c,r=t[j][l]; print(j,l,mp.nstr(mp.mpf(c)/S-q,5),'rad',mp.nstr(mp.mpf(r)/S,5))
src=f'''import TabCore0515
import Log2_100
import NuK0514

/-! # 0515: kernel-checked table of `M⁺(j,l) = ∫ log(1+x) P_j P_l` (j < 64, l < 191 − j), scale `2^256`.
Generated by `gen_mp.py`. Candidate only. -/

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace RHMpTab0515
open RHBall0504 RHBallVec0504 RHRec2D0515 RHTabCore0515

def mu0B : Ball := ({mu0[0]}, {mu0[1]})

def muB (l : ℕ) : Ball := if l = 0 then mu0B else ratBall (2 ^ 256) (if l % 2 = 1 then 2 else -2) (l * (l + 1))

def base : List Ball := (List.range 191).map muB

{lean_row_defs(t)}

theorem tab_base : tab.getD 0 [] = base := by decide +kernel
theorem tab_chk1 : chk1 tab = true := by decide +kernel
theorem tab_chk : chkFrom 0 tab = true := by decide +kernel

end RHMpTab0515
'''
open('MpTabData0515.lean','w').write(src)
print('bytes',len(src))
