# 0515: N (log^2(1+x)) and K (log(1+x)log(1-x)) tables, S = 2^256, rows j<64, base length 127.
from gen_tab import *
from fractions import Fraction as Fr
S=2**256
LC='<DEV>/tool_trials/leancert_0455/'
l2lo=lean_rat(LC+'Log2_100.lean','lo'); l2hi=lean_rat(LC+'Log2_100.lean','hi')
pilo=lean_rat(LC+'PiBounds0466.lean','piLo'); pihi=lean_rat(LC+'PiBounds0466.lean','piHi')
print(float(l2lo),float(pilo),float(pihi-pilo))
L2B=ball_of_bounds(S,l2lo,l2hi); PiB=ball_of_bounds(S,pilo,pihi)
Pi2B=mulB(S,PiB,PiB)
def muB(l): return ball_of_bounds(S,2*l2lo-2,2*l2hi-2) if l==0 else ratBall(S,2 if l%2==1 else -2,l*(l+1))
hB=[(0,0)]
for n in range(200): hB.append(add(hB[-1],ratBall(S,1,n+1)))
nu0B=add(sub(smul(2,1,mulB(S,L2B,L2B)),smul(4,1,L2B)),ratBall(S,4,1))
def nuB(l):
  if l==0: return nu0B
  sg=4 if l%2==1 else -4; D=l*(l+1)
  return add(smul(sg,D,L2B),smul(-sg,D,add(hB[l-1],hB[l+1])))
def kaB(l):
  if l==0: return sub(nu0B,smul(1,3,Pi2B))
  if l%2==1: return (0,0)
  D=l*(l+1); return add(smul(-4,D,L2B),smul(2,D,muB(l)))
import mpmath as mp
mp.mp.dps=80
for name,fb,w in [('N',nuB,lambda u: mp.log(1+u)**2),('K',kaB,lambda u: mp.log(1+u)*mp.log(1-u))]:
  base=[fb(l) for l in range(127)]
  t=rows(base,64)
  print(name,'lens',len(t[0]),len(t[-1]),'max radius bits',max(r for row in t for c,r in row).bit_length())
  for (j,l) in [(0,0),(5,7),(63,63),(40,30)]:
    q=mp.quad(lambda u: w(u)*mp.legendre(j,u)*mp.legendre(l,u),mp.linspace(-1,1,9))
    c,r=t[j][l]; print(' ',j,l,mp.nstr(mp.mpf(c)/S-q,5),'rad',mp.nstr(mp.mpf(r)/S,5))
  src=f'''import TabCore0515
import BaseNK0515

/-! # 0515: kernel-checked table of `{name}(j,l) = ∫ w P_j P_l`, w = {"log²(1+x)" if name=="N" else "log(1+x) log(1−x)"} (j < 64, l < 127 − j), scale `2^256`.
Generated by `gen_nk.py`. Candidate only. -/

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace RH{name}Tab0515
open RHBall0504 RHBallVec0504 RHRec2D0515 RHTabCore0515 RHBaseNK0515

{lean_row_defs(t)}

theorem tab_base : tab.getD 0 [] = {"nuBase" if name=="N" else "kaBase"} := by decide +kernel
theorem tab_chk1 : chk1 tab = true := by decide +kernel
theorem tab_chk : chkFrom 0 tab = true := by decide +kernel

end RH{name}Tab0515
'''
  open(f'{name}TabData0515.lean','w').write(src); print(' bytes',len(src))
print('L2B',L2B); print('PiB',PiB)
