# 0522: γ (Gam0522) and ρ + final check (Rho0522), exact mirror of the Lean definitions below.
import re, pickle, glob, math, sys, os
from fractions import Fraction as Fr
from ballops import *
from gen_tab import rows, ratBall, ball_of_bounds
S=2**256
TR='<DEV>/tool_trials/rh_trunc_0500/'
C=open('../20260926_0521/Const0521.lean').read()
def lb(name): m=re.search(r'def '+name+r' : Ball := \((-?\d+), (\d+)\)',C); return (int(m.group(1)),int(m.group(2)))
wB={m:lb('w%dB'%m) for m in (2,3,4)}
F=pickle.load(open('F.pkl','rb')); OO=pickle.load(open('OO.pkl','rb'))
# N,K,M+ tables regenerated exactly as in 0515
LC='<DEV>/tool_trials/leancert_0455/'
def lean_rat(path,name):
  t=open(path).read(); m=re.search(r'def '+name+r' : ℚ := (-?\d+) ?/ ?(\d+)',t); return Fr(int(m.group(1)),int(m.group(2)))
from gen_tab import mulB as _mulB
g6=open('../20260926_0521/gen_g6.py').read()
exec(g6.split('# ---- moment tables (same generation as 0515) ----')[1].split('# ---- M^kappa tables')[0], globals())
# prSpecT from PrRun files
spec={}
for f in glob.glob(TR+'PrRun0511_g*.lean')+glob.glob(TR+'PrRun2_0511_g*.lean'):
  t=open(f).read()
  for m in re.finditer(r'def spec_(\d+) : List \(\(ℤ × ℕ\) × \(ℤ × ℕ\)\) :=\s*\[(.*?)\]\n',t,re.S):
    n=int(m.group(1)); body=m.group(2)
    pairs=re.findall(r'\(\((-?\d+), (\d+)\), \((-?\d+), (\d+)\)\)',body)
    spec[n]=[((int(a),int(b)),(int(c),int(d))) for a,b,c,d in pairs]
print('spec rows',len(spec),min(spec),max(spec),len(spec[0]))
def neg(b): return (-b[0],b[1])
def gzz(L,i,k): return gz(L[i],k) if i<len(L) else (0,0)
def OOb(a,b,i,k): return gzz(OO['OO%d%d'%(a,b)],i,k) if a<=b else gzz(OO['OO%d%d'%(b,a)],k,i)
W0sq=mulB(S,wB[2],wB[2])
def gamB(i,k):
  g=smul(1,2,add(gzz(Nt,i,k),gzz(Kt,i,k)))
  for a in (2,3,4): g=add(g,mulB(S,wB[a],add(gzz(F[a],i,k),gzz(F[a],k,i))))
  for a in (2,3,4):
    for b in (2,3,4): g=add(g,smul(2,1,mulB(S,mulB(S,wB[a],wB[b]),OOb(a,b,i,k))))
  return add(g,mulB(S,W0sq,add(gzz(OO['XX'],i,k),gzz(OO['XX'],k,i))))
def deg(o,i): return 2*i+(1 if o else 0)
gam={o:[[gamB(deg(o,ii),deg(o,kk)) for kk in range(32)] for ii in range(32)] for o in (False,True)}
def Tb(i,k):
  e=spec[i][k][0] if k<len(spec[i]) else (0,0); return (e[0]*2**128, e[1]*2**128)
def sigB(i,k): return add(gzz(Mp,i,k),smul(2,1,Tb(i,k)))
def rhoB(o,ii,kk):
  di,dk=deg(o,ii),deg(o,kk); acc=(0,0)
  for m in range(64):
    km=deg(o,m); acc=add(acc,smul(2*km+1,2,mulB(S,sigB(di,km),sigB(dk,km))))
  return sub(gam[o][ii][kk],acc)
rho={o:[[rhoB(o,ii,kk) for kk in range(32)] for ii in range(32)] for o in (False,True)}
pickle.dump(dict(gam=gam,rho=rho),open('rho.pkl','wb'))
# sqrt balls
sq={}
for n in range(64):
  a=Fr(2*n+1,2); c=math.isqrt((2*n+1)*S*S//2); r=2
  assert (c-r)**2*2 <= (2*n+1)*S*S <= (c+r)**2*2 and c-r>=0
  sq[n]=(c,r)
# B rational
os.chdir('../20260925_0512'); sys.path.insert(0,'.'); sys.path.insert(0,'../20260925_0509'); sys.path.insert(0,'../20260924_0505')
import t5mirror as tm; os.chdir('../20260926_0522')
def qBall(q): return ((q.numerator*S)//q.denominator,1)
eta=Fr(1,10**4); delta=Fr(1,10**14); Lub=Fr(81,100)
for o in (False,True):
  Bp=[[mulB(S,qBall(tm.BQ[o](ii,j)),sq[deg(o,ii)]) for j in range(32)] for ii in range(32)]
  tot=0; Esum=0
  for j in range(32):
    col=[Bp[ii][j] for ii in range(32)]
    y=[dotB(S,rho[o][ii],col) for ii in range(32)]
    T=dotB(S,col,y); tot+=T[0]+T[1]
    cs=sum(abs(qBall(tm.BQ[o](ii,j))[0])+1 for ii in range(32)); Esum+=cs*cs
  dM=Fr(1230379,10**6) if o else Fr(1409795,10**6)
  lhs=(1+eta)*Fr(tot,S)+(1+1/eta)*2*Lub*delta**2*Fr(Esum,S*S)
  print('odd' if o else 'even','lhs/dM',float(lhs/dM),'ok',lhs<=Fr(99,100)*dM)
pickle.dump(sq,open('sq.pkl','wb'))
# ---------------- Lean generation ----------------
def rowdefs(name,t):
  s=''.join(f'def {name}_{j} : List Ball := [' + ', '.join(f'({c}, {r})' for c,r in row) + ']\n' for j,row in enumerate(t))
  return s+f'def {name} : List (List Ball) := [' + ', '.join(f'{name}_{j}' for j in range(len(t))) + ']\n'
pairs=[(a,b) for a in (2,3,4) for b in (2,3,4)]
oob='\n'.join(f'  | {a}, {b}, i, k => gzz RHOO{min(a,b)}{max(a,b)}_0522.tab ' + ('i k' if a<=b else 'k i') for a,b in pairs)
src=f'''import NTabData0515
import KTabData0515
import FFm2_0522
import FF3_0522
import FFm4_0522
import OO22_0522
import OO23_0522
import OO24_0522
import OO33_0522
import OO34_0522
import OO44_0522
import XX_0522

/-! # 0522: the singular Gram entries `γ_ik` (32×32 per parity) as checked literal tables.
`γ = ½(N+K) + Σ_a w_a (F_a(i,k)+F_a(k,i)) + Σ_{{a,b}} 2 w_a w_b OO(i,k,a,b) + w_2²(X(i,k)+X(k,i))`.
Generated by `gen_final.py`. Candidate only. -/

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace RHGam0522
open RHBall0504 RHBallVec0504 RHBallDot0509 RHConditionalLog5

def gzz (L : List (List Ball)) (i k : ℕ) : Ball := gz (L.getD i []) k

def wBm : ℕ → Ball
  | 2 => RHConst0521.w2B
  | 3 => RHConst0521.w3B
  | _ => RHConst0521.w4B

def Ftab : ℕ → List (List Ball)
  | 2 => RHFFm2_0522.Fm
  | 3 => RHFF3_0522.Fm
  | _ => RHFFm4_0522.Fm

def OOb : ℕ → ℕ → ℕ → ℕ → Ball
{oob}
  | _, _, _, _ => (0, 0)

def fterm (a i k : ℕ) : Ball := mulB (2 ^ 256) (wBm a) (add (gzz (Ftab a) i k) (gzz (Ftab a) k i))
def oterm (a b i k : ℕ) : Ball := smul 2 1 (mulB (2 ^ 256) (mulB (2 ^ 256) (wBm a) (wBm b)) (OOb a b i k))
def xterm (i k : ℕ) : Ball :=
  mulB (2 ^ 256) (mulB (2 ^ 256) RHConst0521.w2B RHConst0521.w2B) (add (gzz RHXX_0522.tab i k) (gzz RHXX_0522.tab k i))

def gamB (i k : ℕ) : Ball :=
  add (smul 1 2 (add (gzz RHNTab0515.tab i k) (gzz RHKTab0515.tab i k)))
    (add (add (fterm 2 i k) (add (fterm 3 i k) (fterm 4 i k)))
      (add (add (add (oterm 2 2 i k) (add (oterm 2 3 i k) (oterm 2 4 i k)))
             (add (add (oterm 3 2 i k) (add (oterm 3 3 i k) (oterm 3 4 i k)))
                  (add (oterm 4 2 i k) (add (oterm 4 3 i k) (oterm 4 4 i k)))))
        (xterm i k)))

def gamTab (o : Bool) : List (List Ball) :=
  (List.range 32).map (fun ii => (List.range 32).map (fun kk => gamB (degree o ii) (degree o kk)))

{rowdefs('gamE',gam[False])}
{rowdefs('gamO',gam[True])}
theorem gamE_eq : gamE = gamTab false := by decide +kernel
theorem gamO_eq : gamO = gamTab true := by decide +kernel

end RHGam0522
'''
open('Gam0522.lean','w').write(src); print('Gam bytes',len(src))
sqlist=', '.join(f'({sq[n][0]}, {sq[n][1]})' for n in range(64))
src=f'''import Gam0522
import MpTabData0515
import PrAll0512
import BQ0512
import EntryBall0512

/-! # 0522: `σ_ik = M⁺_ik + 2T_ik`, `ρ = γ − Σ_m (2k_m+1)/2 σσ` (literal) and the final G6c numeric check
`(1+η) Σ_j B′ᵀρB′ + (1+1/η)·2·(81/100)·δ²·Σ_j (Σ_i |B_ij|)² ≤ (99/100)·dM`, `η = 10⁻⁴`, `δ = 10⁻¹⁴`,
`B′_ij = B_ij √((2 deg i + 1)/2)`. Generated by `gen_final.py`. Candidate only. -/

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace RHRho0522
open RHBall0504 RHBallVec0504 RHBallDot0509 RHConditionalLog5 RHGam0522 RHEntryBall0512

def Tb (i k : ℕ) : Ball :=
  ((((RHPrAll0512.prSpecT i).getD k ((0, 0), (0, 0))).1.1 * 2 ^ 128,
    ((RHPrAll0512.prSpecT i).getD k ((0, 0), (0, 0))).1.2 * 2 ^ 128))

def sigB (i k : ℕ) : Ball := add (gzz RHMpTab0515.tab i k) (smul 2 1 (Tb i k))

def rhoSum (o : Bool) (di dk : ℕ) : ℕ → Ball
  | 0 => (0, 0)
  | m + 1 => add (rhoSum o di dk m)
      (smul (2 * (degree o m : ℤ) + 1) 2 (mulB (2 ^ 256) (sigB di (degree o m)) (sigB dk (degree o m))))

def rhoB (o : Bool) (G : List (List Ball)) (ii kk : ℕ) : Ball :=
  sub (gzz G ii kk) (rhoSum o (degree o ii) (degree o kk) 64)

def rhoTab (o : Bool) (G : List (List Ball)) : List (List Ball) :=
  (List.range 32).map (fun ii => (List.range 32).map (fun kk => rhoB o G ii kk))

{rowdefs('rhoE',rho[False])}
{rowdefs('rhoO',rho[True])}
theorem rhoE_eq : rhoE = rhoTab false gamE := by decide +kernel
theorem rhoO_eq : rhoO = rhoTab true gamO := by decide +kernel

/-- balls for `√((2n+1)/2)`, `n < 64` -/
def sqL : List Ball := [{sqlist}]
def sqOK (n : ℕ) : Bool :=
  let b := gz sqL n
  decide (0 ≤ b.1 - b.2 ∧ (b.1 - b.2) ^ 2 * 2 ≤ (2 * (n : ℤ) + 1) * (2 ^ 256) ^ 2 ∧
    (2 * (n : ℤ) + 1) * (2 ^ 256) ^ 2 ≤ (b.1 + b.2) ^ 2 * 2)
theorem sq_ok : (List.range 64).all sqOK = true := by decide +kernel

def Qn (o : Bool) (i j : ℕ) : ℚ := ((if o then RHBQ0512.oddTab else RHBQ0512.evenTab).getD i []).getD j 0
def Bp (o : Bool) (i j : ℕ) : Ball := mulB (2 ^ 256) (qBall (2 ^ 256) (Qn o i j)) (gz sqL (degree o i))
def colB (o : Bool) (j : ℕ) : List Ball := (List.range 32).map (fun i => Bp o i j)
def Tj (o : Bool) (R : List (List Ball)) (j : ℕ) : Ball :=
  dotB (2 ^ 256) (colB o j) (R.map (fun row => dotB (2 ^ 256) row (colB o j)))
def tot (o : Bool) (R : List (List Ball)) : ℤ := ((List.range 32).map (fun j => (Tj o R j).1 + (Tj o R j).2)).sum
def csum (o : Bool) (j : ℕ) : ℕ := ((List.range 32).map (fun i => (qBall (2 ^ 256) (Qn o i j)).1.natAbs + 1)).sum
def Esum (o : Bool) : ℕ := ((List.range 32).map (fun j => csum o j ^ 2)).sum
def dMq (o : Bool) : ℚ := if o then 1230379 / 1000000 else 1409795 / 1000000

def check (o : Bool) (R : List (List Ball)) : Bool :=
  decide ((1 + 1 / 10 ^ 4 : ℚ) * ((tot o R : ℚ) / 2 ^ 256) +
    (1 + 10 ^ 4 : ℚ) * 2 * (81 / 100) * (1 / 10 ^ 28) * ((Esum o : ℚ) / (2 ^ 256) ^ 2) ≤ 99 / 100 * dMq o)

theorem final_even : check false rhoE = true := by decide +kernel
theorem final_odd : check true rhoO = true := by decide +kernel

end RHRho0522
'''
open('Rho0522.lean','w').write(src); print('Rho bytes',len(src))
