# 0522: chunked F stage for m = 2, 4 (8 chunks of 8 rows) + row module + combiner
import pickle
F=pickle.load(open('F.pkl','rb'))
def rowdefs(name,t):
  s=''.join(f'def {name}_{j} : List Ball := [' + ', '.join(f'({c}, {r})' for c,r in row) + ']\n' for j,row in enumerate(t))
  return s+f'def {name} : List (List Ball) := [' + ', '.join(f'{name}_{j}' for j in range(len(t))) + ']\n'
hdr='set_option maxRecDepth 100000\nset_option maxHeartbeats 0\n\n'
for m in (2,4):
  open(f'FRow{m}_0522.lean','w').write(f'''import FY{m}_0522
import FamDataA_0522

/-! # 0522: the F-stage row function for m = {m}. Candidate only. -/

namespace RHFRow{m}_0522
open RHBall0504 RHBallVec0504 RHBallDot0509 RHPrBall0511 RHG6Core0522 RHFamDefs0522

def fRow (A : List Ball) : List Ball :=
  (List.zip RHFamB_0522.famB{m} RHFY{m}_0522.Y).map (fun p =>
    mulB (2 ^ 256) (alphaB {m}) (add (mulB (2 ^ 256) RHConst0521.ell{m} (dB (2 ^ 256) A p.1)) (dotB (2 ^ 256) A p.2)))

end RHFRow{m}_0522
''')
  for c in range(8):
    rows=F[m][8*c:8*c+8]
    open(f'FFc{m}_{c}_0522.lean','w').write(f'''import FRow{m}_0522

/-! # 0522: F stage m = {m}, rows {8*c}..{8*c+7} (chunk {c}). Generated by `gen_ffchunk.py`. Candidate only. -/

{hdr}namespace RHFFc{m}_{c}_0522
open RHBall0504 RHFRow{m}_0522

{rowdefs('FmC',rows)}
theorem c_eq : FmC = (List.range 8).map (fun r => fRow (RHFamA_0522.famA{m}.getD ({8*c} + r) [])) := by decide +kernel

end RHFFc{m}_{c}_0522
''')
  imports=''.join(f'import FFc{m}_{c}_0522\n' for c in range(8))
  chunk_match='\n'.join(f'  | {c} => RHFFc{m}_{c}_0522.FmC' for c in range(7))+f'\n  | _ => RHFFc{m}_7_0522.FmC'
  open(f'FFm{m}_0522.lean','w').write(f'''{imports}
/-! # 0522: F stage m = {m} assembled from 8 chunks: `Fm.getD i [] = fRow (famA.getD i [])` (i < 64). Candidate only. -/

{hdr}namespace RHFFm{m}_0522
open RHBall0504 RHFRow{m}_0522

def chunk : ℕ → List (List Ball)
{chunk_match}

def Fm : List (List Ball) := {' ++ '.join(f'RHFFc{m}_{c}_0522.FmC' for c in range(8))}

theorem Fm_chunk : (List.range 64).all (fun i => Fm.getD i [] == (chunk (i / 8)).getD (i % 8) []) = true := by
  decide +kernel

theorem key (a i : ℕ) (hr : i % 8 < 8) :
    ((List.range 8).map (fun r => fRow (RHFamA_0522.famA{m}.getD (a + r) []))).getD (i % 8) [] =
      fRow (RHFamA_0522.famA{m}.getD (a + i % 8) []) := by
  rw [List.getD_eq_getElem?_getD, List.getElem?_map, List.getElem?_range hr]; rfl

theorem chunk_row (i : ℕ) (hi : i < 64) : (chunk (i / 8)).getD (i % 8) [] = fRow (RHFamA_0522.famA{m}.getD i []) := by
  have hr : i % 8 < 8 := Nat.mod_lt _ (by norm_num)
  have e : 8 * (i / 8) + i % 8 = i := Nat.div_add_mod i 8
  have hc : i / 8 < 8 := by omega
  interval_cases h : i / 8 <;> simp only [chunk]
  · rw [RHFFc{m}_0_0522.c_eq, key _ _ hr, show 0 + i % 8 = i by omega]
  · rw [RHFFc{m}_1_0522.c_eq, key _ _ hr, show 8 + i % 8 = i by omega]
  · rw [RHFFc{m}_2_0522.c_eq, key _ _ hr, show 16 + i % 8 = i by omega]
  · rw [RHFFc{m}_3_0522.c_eq, key _ _ hr, show 24 + i % 8 = i by omega]
  · rw [RHFFc{m}_4_0522.c_eq, key _ _ hr, show 32 + i % 8 = i by omega]
  · rw [RHFFc{m}_5_0522.c_eq, key _ _ hr, show 40 + i % 8 = i by omega]
  · rw [RHFFc{m}_6_0522.c_eq, key _ _ hr, show 48 + i % 8 = i by omega]
  · rw [RHFFc{m}_7_0522.c_eq, key _ _ hr, show 56 + i % 8 = i by omega]

theorem Fm_row (i : ℕ) (hi : i < 64) : Fm.getD i [] = fRow (RHFamA_0522.famA{m}.getD i []) := by
  have h := (List.all_eq_true.mp Fm_chunk) i (List.mem_range.mpr hi)
  simp only [beq_iff_eq] at h
  rw [h, chunk_row i hi]

end RHFFm{m}_0522
''')
print('ok')
