# 0522: OO(a<=b) and X stage modules. OO(i,k,a,b), a<b: α_b·dB(cross(a,b)_i, famB_b_k); a=b: α_a·dB(famB_a_i, famB_a_k); X: (1−σ2)·dB(Xm_i, Xp_k)
import re, pickle
from ballops import *
S=2**256
C=open('../20260926_0521/Const0521.lean').read()
def lb(name): m=re.search(r'def '+name+r' : Ball := \((-?\d+), (\d+)\)',C); return (int(m.group(1)),int(m.group(2)))
fams=pickle.load(open('fams.pkl','rb'))
sig={m:lb('sig%d'%m) for m in (2,3,4)}
alpha={m:sub((S,0),smul(1,2,sig[m])) for m in (2,3,4)}
oneMs=sub((S,0),sig[2])
def rowdefs(name,t):
  s=''.join(f'def {name}_{j} : List Ball := [' + ', '.join(f'({c}, {r})' for c,r in row) + ']\n' for j,row in enumerate(t))
  return s+f'def {name} : List (List Ball) := [' + ', '.join(f'{name}_{j}' for j in range(len(t))) + ']\n'
out={}
specs=[]
for a in (2,3,4):
  for b in (2,3,4):
    if a<b: specs.append((f'OO{a}{b}',alpha[b],f'alphaB {b}',fams[f'cr{a}{b}'],f'RHFamX_0522.cr{a}{b}',fams[f'famB{b}'],f'RHFamB_0522.famB{b}'))
    elif a==b: specs.append((f'OO{a}{b}',alpha[a],f'alphaB {a}',fams[f'famB{a}'],f'RHFamB_0522.famB{a}',fams[f'famB{a}'],f'RHFamB_0522.famB{a}'))
specs.append(('XX',oneMs,'oneMsB',fams['famXm'],'RHFamX_0522.famXm',fams['famXp'],'RHFamX_0522.famXp'))
for name,al,alL,L,LL,R,RL in specs:
  t=[[mulB(S,al,dB(S,Li,Rk)) for Rk in R] for Li in L]
  out[name]=t
  src=f'''import FamDataB_0522
import FamDataX_0522

/-! # 0522: overlap stage `{name}` (64×64): `α·dB(L_i, R_k)`. Generated by `gen_oo.py`. Candidate only. -/

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace RH{name}_0522
open RHBall0504 RHBallVec0504 RHBallDot0509 RHPrBall0511 RHFamDefs0522

{rowdefs('tab',t)}
theorem tab_eq : tab = {LL}.map (fun Li => {RL}.map (fun Rk => mulB (2 ^ 256) ({alL}) (dB (2 ^ 256) Li Rk))) := by
  decide +kernel

end RH{name}_0522
'''
  open(f'{name}_0522.lean','w').write(src); print(name,len(src))
pickle.dump(out,open('OO.pkl','wb'))
