# 0522: literal Af families at 2^256 (FamDefs0522 = ball constants; FamData0522_{A,B,X})
import re
from ballops import *
S=2**256
C=open('../20260926_0521/Const0521.lean').read()
def lb(name): m=re.search(r'def '+name+r' : Ball := \((-?\d+), (\d+)\)',C); return (int(m.group(1)),int(m.group(2)))
sig={m:lb('sig%d'%m) for m in (2,3,4)}
def neg(b): return (-b[0],b[1])
alpha={m:sub((S,0),smul(1,2,sig[m])) for m in (2,3,4)}
g2={m:smul(1,2,sig[m]) for m in (2,3,4)}
g1={m:neg(smul(1,2,sig[m])) for m in (2,3,4)}
cross={(a,b):sub(smul(1,2,sig[b]),sig[a]) for a,b in ((2,3),(2,4),(3,4))}
oneMs=sub((S,0),sig[2]); nsig=neg(sig[2])
fams={}
for m in (2,3,4): fams['famA%d'%m]=('alphaB %d'%m,'g2B %d'%m,afAll(S,alpha[m],g2[m],64))
for m in (2,3,4): fams['famB%d'%m]=('alphaB %d'%m,'g1B %d'%m,afAll(S,alpha[m],g1[m],64))
for a,b in cross: fams['cr%d%d'%(a,b)]=('alphaB %d'%b,'crossB %d %d'%(a,b),afAll(S,alpha[b],cross[(a,b)],64))
fams['famXm']=('oneMsB','nsigB',afAll(S,oneMs,nsig,64)); fams['famXp']=('oneMsB','sigB 2',afAll(S,oneMs,sig[2],64))
import pickle; pickle.dump({k:v[2] for k,v in fams.items()},open('fams.pkl','wb'))
groups={'A':['famA2','famA3','famA4'],'B':['famB2','famB3','famB4'],'X':['cr23','cr24','cr34','famXm','famXp']}
for g,names in groups.items():
  src=f'''import FamDefs0522

/-! # 0522: literal Af families (group {g}), checked against `afAll`. Generated by `gen_fam.py`. Candidate only. -/

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace RHFam{g}_0522
open RHBall0504 RHPrBall0511 RHFamDefs0522

'''
  for nm in names:
    aB,gB,t=fams[nm]
    for j,row in enumerate(t):
      src+=f'def {nm}_{j} : List Ball := [' + ', '.join(f'({c}, {r})' for c,r in row) + ']\n'
    src+=f'def {nm} : List (List Ball) := [' + ', '.join(f'{nm}_{j}' for j in range(len(t))) + ']\n'
    src+=f'theorem {nm}_eq : {nm} = afAll (2 ^ 256) ({aB}) ({gB}) 64 := by decide +kernel\n\n'
  src+=f'end RHFam{g}_0522\n'
  open(f'FamData{g}_0522.lean','w').write(src); print(g,len(src))
