# 0522: F stage per shift m: literal Mm (64x64), Ym = [dotRows Mm B_k], Fm[i][k] = mulB α (add (mulB ℓ (dB A_i B_k)) (dotB A_i Y_k))
import re, pickle, sys
from ballops import *
from gen_tab import rows, ratBall, ball_of_bounds
sys.path.insert(0,'../20260926_0521'); from gen_lam import lamBase
from fractions import Fraction as Fr
S=2**256
C=open('../20260926_0521/Const0521.lean').read()
def lb(name): m=re.search(r'def '+name+r' : Ball := \((-?\d+), (\d+)\)',C); return (int(m.group(1)),int(m.group(2)))
fams=pickle.load(open('fams.pkl','rb'))
LC='<DEV>/tool_trials/leancert_0455/'
def lean_rat(path,name):
  t=open(path).read(); m=re.search(r'def '+name+r' : ℚ := (-?\d+) ?/ ?(\d+)',t); return Fr(int(m.group(1)),int(m.group(2)))
l2lo=lean_rat(LC+'Log2_100.lean','lo'); l2hi=lean_rat(LC+'Log2_100.lean','hi')
Mp=rows([ball_of_bounds(S,2*l2lo-2,2*l2hi-2)]+[ratBall(S,2 if l%2==1 else -2,l*(l+1)) for l in range(1,191)],64)
def neg(b): return (-b[0],b[1])
def signed(j,row): return [b if (j+jj)%2==0 else neg(b) for jj,b in enumerate(row)]
def mkM(Mk): return [vadd(signed(j,Mp[j][:64]),Mk[j][:64]) for j in range(64)]
def dotRows(Ml,Bl): return [dotB(S,row,Bl) for row in Ml]
def rowdefs(name,t): 
  s=''.join(f'def {name}_{j} : List Ball := [' + ', '.join(f'({c}, {r})' for c,r in row) + ']\n' for j,row in enumerate(t))
  return s+f'def {name} : List (List Ball) := [' + ', '.join(f'{name}_{j}' for j in range(len(t))) + ']\n'
out={}
for m in (2,3,4):
  Mk=rows(lamBase(S,lb('kap%d'%m),170,127),64)
  Mm=mkM(Mk); A=fams['famA%d'%m]; B=fams['famB%d'%m]
  Y=[dotRows(Mm,Bk) for Bk in B]
  al=sub((S,0),smul(1,2,lb('sig%d'%m))); ell=lb('ell%d'%m)
  Fm=[[mulB(S,al,add(mulB(S,ell,dB(S,A[i],B[k])),dotB(S,A[i],Y[k]))) for k in range(64)] for i in range(64)]
  out[m]=Fm
  # module M+Y
  src=f'''import G6Core0522
import FamDataB_0522
import MpTabData0515
import MkTabData{m}_0521

/-! # 0522: F stage (m = {m}), part 1: matrix `Mm = ((−1)^{{j+j'}} M⁺ + Mκ)` (64×64) and `Y_k = Mm B_k`.
Generated by `gen_fstage.py`. Candidate only. -/

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace RHFY{m}_0522
open RHBall0504 RHBallVec0504 RHBallDot0509 RHG6Core0522

def signed (j : ℕ) (row : List Ball) : List Ball := mapI (fun jj b => if (j + jj) % 2 = 0 then b else neg b) 0 row
def mkRow (j : ℕ) : List Ball :=
  vadd (signed j ((RHMpTab0515.tab.getD j []).take 64)) ((RHMkTab{m}_0521.tab.getD j []).take 64)

{rowdefs('Mm',Mm)}
theorem Mm_eq : Mm = (List.range 64).map mkRow := by decide +kernel

{rowdefs('Y',Y)}
theorem Y_eq : Y = RHFamB_0522.famB{m}.map (fun Bk => dotRows (2 ^ 256) Mm Bk) := by decide +kernel

end RHFY{m}_0522
'''
  open(f'FY{m}_0522.lean','w').write(src)
  src=f'''import FY{m}_0522
import FamDataA_0522

/-! # 0522: F stage (m = {m}), part 2: `F_ik = α(ℓ·dB(A_i,B_k) + A_i·Y_k)` (64×64). Generated by `gen_fstage.py`.
Candidate only. -/

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace RHFF{m}_0522
open RHBall0504 RHBallVec0504 RHBallDot0509 RHPrBall0511 RHG6Core0522 RHFamDefs0522

def fRow (A : List Ball) : List Ball :=
  (List.zip RHFamB_0522.famB{m} RHFY{m}_0522.Y).map (fun p =>
    mulB (2 ^ 256) (alphaB {m}) (add (mulB (2 ^ 256) RHConst0521.ell{m} (dB (2 ^ 256) A p.1)) (dotB (2 ^ 256) A p.2)))

{rowdefs('Fm',Fm)}
theorem Fm_eq : Fm = RHFamA_0522.famA{m}.map fRow := by decide +kernel

end RHFF{m}_0522
'''
  open(f'FF{m}_0522.lean','w').write(src)
pickle.dump(out,open('F.pkl','wb'))
print('ok', OPS)
