import LamDef0521
import PrEncl0511
import FRed0516
import Coarse0509
import LeanCert.Core.IntervalRat.Taylor

/-! # 0521: constant balls at scale `2^256` for the G6c pipeline (generated by `gen_const.py`)

For `m = 2, 3, 4` (`σ = σ m = log m / L`): `σ`, `w_m`, `κ = (1−σ/2)/(1+σ/2)`,
`ℓ = log(1−σ/2) + log(1+σ/2)`. LeanCert `logComputable` for the rational log bounds. -/

set_option maxRecDepth 100000
set_option maxHeartbeats 10000000

open LeanCert.Core

namespace RHConst0521
open RHBall0504 RHCoarse0509 RHPrEncl0511 RHBallMisc0512 RHLog5Bridge

lemma hS : 0 < (2:ℕ) ^ 256 := by positivity

lemma mem_bounds {S : ℕ} (hS : 0 < S) {x : ℝ} {b : Ball} (h : mem S x b) :
    ((b.1 : ℝ) - b.2) / S ≤ x ∧ x ≤ ((b.1 : ℝ) + b.2) / S := by
  unfold mem at h
  have hS' : (0:ℝ) < S := by exact_mod_cast hS
  rw [abs_le] at h
  constructor
  · rw [sub_div]; linarith [h.2]
  · rw [add_div]; linarith [h.1]

lemma kappa_bounds {σ lo hi : ℝ} (h1 : lo ≤ σ) (h2 : σ ≤ hi) (h0 : 0 ≤ lo) (h3 : hi < 2) :
    (2 - hi) / (2 + hi) ≤ (1 - σ / 2) / (1 + σ / 2) ∧ (1 - σ / 2) / (1 + σ / 2) ≤ (2 - lo) / (2 + lo) := by
  have e : (1 - σ / 2) / (1 + σ / 2) = (2 - σ) / (2 + σ) := by field_simp
  rw [e]
  constructor
  · rw [div_le_div_iff₀ (by linarith) (by linarith)]; nlinarith
  · rw [div_le_div_iff₀ (by linarith) (by linarith)]; nlinarith

lemma ell_eq {σ : ℝ} (h0 : 0 ≤ σ) (h2 : σ < 2) :
    Real.log (1 - σ / 2) + Real.log (1 + σ / 2) = Real.log (1 - σ ^ 2 / 4) := by
  rw [← Real.log_mul (by linarith) (by linarith)]; congr 1; ring

theorem kap_gen {S : ℕ} (hS : 0 < S) {σ : ℝ} {sB kB : Ball} (hσ : mem S σ sB)
    (c0 : (0 : ℚ) ≤ ((sB.1 : ℚ) - sB.2) / S) (c3 : ((sB.1 : ℚ) + sB.2) / S < 2)
    (c1 : ((kB.1 : ℚ) - kB.2) / S ≤ (2 - ((sB.1 : ℚ) + sB.2) / S) / (2 + ((sB.1 : ℚ) + sB.2) / S))
    (c2 : (2 - ((sB.1 : ℚ) - sB.2) / S) / (2 + ((sB.1 : ℚ) - sB.2) / S) ≤ ((kB.1 : ℚ) + kB.2) / S) :
    mem S ((1 - σ / 2) / (1 + σ / 2)) kB := by
  obtain ⟨h1, h2⟩ := mem_bounds hS hσ
  have r0 : (0:ℝ) ≤ ((sB.1 : ℝ) - sB.2) / S := by exact_mod_cast c0
  have r3 : ((sB.1 : ℝ) + sB.2) / S < 2 := by exact_mod_cast c3
  have d1 : ((kB.1 : ℝ) - kB.2) / S ≤ (2 - ((sB.1 : ℝ) + sB.2) / S) / (2 + ((sB.1 : ℝ) + sB.2) / S) := by
    exact_mod_cast c1
  have d2 : (2 - ((sB.1 : ℝ) - sB.2) / S) / (2 + ((sB.1 : ℝ) - sB.2) / S) ≤ ((kB.1 : ℝ) + kB.2) / S := by
    exact_mod_cast c2
  obtain ⟨k1, k2⟩ := kappa_bounds h1 h2 r0 r3
  exact mem_of_bounds' hS (by linarith) (by linarith)

theorem ell_gen {S : ℕ} (hS : 0 < S) {σ : ℝ} {sB lB : Ball} (hσ : mem S σ sB) {ylo yhi Llo Lhi : ℚ}
    (c0 : (0 : ℚ) ≤ ((sB.1 : ℚ) - sB.2) / S) (c3 : ((sB.1 : ℚ) + sB.2) / S < 2)
    (cy1 : ylo ≤ 1 - (((sB.1 : ℚ) + sB.2) / S) ^ 2 / 4) (cy2 : 1 - (((sB.1 : ℚ) - sB.2) / S) ^ 2 / 4 ≤ yhi)
    (ypos : 0 < ylo) (hlo : (Llo : ℝ) ≤ Real.log ylo) (hhi : Real.log yhi ≤ Lhi)
    (c1 : ((lB.1 : ℚ) - lB.2) / S ≤ Llo) (c2 : Lhi ≤ ((lB.1 : ℚ) + lB.2) / S) :
    mem S (Real.log (1 - σ / 2) + Real.log (1 + σ / 2)) lB := by
  obtain ⟨h1, h2⟩ := mem_bounds hS hσ
  have r0 : (0:ℝ) ≤ ((sB.1 : ℝ) - sB.2) / S := by exact_mod_cast c0
  have r3 : ((sB.1 : ℝ) + sB.2) / S < 2 := by exact_mod_cast c3
  have hσ0 : 0 ≤ σ := le_trans r0 h1
  have hσ2 : σ < 2 := lt_of_le_of_lt h2 r3
  rw [ell_eq hσ0 hσ2]
  have dy1 : (ylo : ℝ) ≤ 1 - (((sB.1 : ℝ) + sB.2) / S) ^ 2 / 4 := by exact_mod_cast cy1
  have dy2 : 1 - (((sB.1 : ℝ) - sB.2) / S) ^ 2 / 4 ≤ (yhi : ℝ) := by exact_mod_cast cy2
  have sq1 : σ ^ 2 ≤ (((sB.1 : ℝ) + sB.2) / S) ^ 2 := pow_le_pow_left₀ hσ0 h2 2
  have sq2 : (((sB.1 : ℝ) - sB.2) / S) ^ 2 ≤ σ ^ 2 := pow_le_pow_left₀ r0 h1 2
  have ypos' : (0:ℝ) < ylo := by exact_mod_cast ypos
  have l1 := Real.log_le_log ypos' (show (ylo : ℝ) ≤ 1 - σ ^ 2 / 4 by linarith)
  have l2 := Real.log_le_log (by nlinarith) (show 1 - σ ^ 2 / 4 ≤ (yhi : ℝ) by linarith)
  have d1 : ((lB.1 : ℝ) - lB.2) / S ≤ Llo := by exact_mod_cast c1
  have d2 : (Lhi : ℝ) ≤ ((lB.1 : ℝ) + lB.2) / S := by exact_mod_cast c2
  exact mem_of_bounds' hS (by linarith) (by linarith)

/-! ### m = 2 -/

def sig2 : Ball := (99737876889709037750541505795144189241467692025121695692871604972719600784807, 1)
def w2B : Ball := (56753069212057959132282400013831633062298827811860916855182730355203350403774, 610039258002298910243340768230674628722091959)
def kap2 : Ball := (46078304995250959563839553606827071860263015927733372868368890815231967861812, 3)
def ell2 : Ball := (-23755802806326413799628509867232101909876302199692228283785911709639873483358, 3)
def ylo2 : ℚ := (81451770232605530310717127905642510403748804066526289078538142399111746995816661 / 100000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℚ)
def yhi2 : ℚ := (40725885116302765155358563952821255201874402033263144539269071199555873497908703 / 50000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℚ)
def Llo2 : ℚ := (-205159117197020537819065352042341012883317609819191338410372021292206042785713452386086603 / 1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℚ)
def Lhi2 : ℚ := (-102579558598510268909532676021170506441658804909595669205186010646103021392852152934550129 / 500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℚ)
private def encLo2 : IntervalRat := IntervalRat.logComputable (IntervalRat.singleton ylo2) 400
private def encHi2 : IntervalRat := IntervalRat.logComputable (IntervalRat.singleton yhi2) 400

theorem sig2_mem : mem (2 ^ 256) (RHSingDef0516.σ 2) sig2 := by
  have h := RHPrEncl0511.sig2_mem
  have hw : within sB2 sig2.1 sig2.2 256 = true := by decide +kernel
  have h' : mem (2 ^ (256 + 256)) (Real.log 2 / halfWidth) sB2 := by simpa [S512] using h
  have := mem_coarse h' hw
  simpa [RHSingDef0516.σ] using this

theorem w2_mem : mem (2 ^ 256) RHPrSum0511.w2 w2B := by
  have h := RHPrEncl0511.w2_mem
  have hw : within wB2 w2B.1 w2B.2 256 = true := by decide +kernel
  have h' : mem (2 ^ (256 + 256)) RHPrSum0511.w2 wB2 := by simpa [S512] using h
  exact mem_coarse h' hw

theorem kap2_mem : mem (2 ^ 256) ((1 - RHSingDef0516.σ 2 / 2) / (1 + RHSingDef0516.σ 2 / 2)) kap2 :=
  kap_gen hS sig2_mem (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)

lemma logLo2 : ((Llo2 : ℚ) : ℝ) ≤ Real.log ylo2 := by
  have ypos : (0:ℚ) < ylo2 := by decide +kernel
  have e := IntervalRat.mem_logComputable (IntervalRat.mem_singleton ylo2) (by simpa [IntervalRat.singleton] using ypos) 400
  change ((encLo2.lo : ℚ) : ℝ) ≤ Real.log ylo2 ∧ Real.log ylo2 ≤ (encLo2.hi : ℝ) at e
  have f : Llo2 ≤ encLo2.lo := by decide +kernel
  exact le_trans (by exact_mod_cast f) e.1

lemma logHi2 : Real.log yhi2 ≤ ((Lhi2 : ℚ) : ℝ) := by
  have ypos : (0:ℚ) < yhi2 := by decide +kernel
  have e := IntervalRat.mem_logComputable (IntervalRat.mem_singleton yhi2) (by simpa [IntervalRat.singleton] using ypos) 400
  change ((encHi2.lo : ℚ) : ℝ) ≤ Real.log yhi2 ∧ Real.log yhi2 ≤ (encHi2.hi : ℝ) at e
  have f : encHi2.hi ≤ Lhi2 := by decide +kernel
  exact le_trans e.2 (by exact_mod_cast f)

theorem ell2_mem : mem (2 ^ 256) (Real.log (1 - RHSingDef0516.σ 2 / 2) + Real.log (1 + RHSingDef0516.σ 2 / 2)) ell2 :=
  ell_gen hS sig2_mem (ylo := ylo2) (yhi := yhi2) (Llo := Llo2) (Lhi := Lhi2)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    logLo2 logHi2 (by decide +kernel) (by decide +kernel)

/-! ### m = 3 -/

def sig3 : Ball := (158080794771732047189778328175735477673043286346420464993324108332634540931087, 1)
def w3B : Ball := (73445081178203970801035633147401817325942183181765247148303422062129216569209, 546280656400418264291462144660248702856382145)
def kap3 : Ball := (21842123232333246197030687816024900087865216502709023982366437308651510646698, 3)
def ell3 : Ball := (-72632682629257534511425645884103263155397159414620699529378090146885940128758, 3)
def ylo3 : ℚ := (53404878324936121846027217222806924574246613234794338477700675753946076374362413 / 100000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℚ)
def yhi3 : ℚ := (53404878324936121846027217222806924574246613234794338477700675753946076374363593 / 100000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℚ)
def Llo3 : ℚ := (-15681702244873710226153186632855445028447970292779366147191069753529989225268578667569463 / 25000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℚ)
def Lhi3 : ℚ := (-313634044897474204523063732657108900568959405855587322943821395070599784505360525671504843 / 500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℚ)
private def encLo3 : IntervalRat := IntervalRat.logComputable (IntervalRat.singleton ylo3) 400
private def encHi3 : IntervalRat := IntervalRat.logComputable (IntervalRat.singleton yhi3) 400

theorem sig3_mem : mem (2 ^ 256) (RHSingDef0516.σ 3) sig3 := by
  have h := RHPrEncl0511.sig3_mem
  have hw : within sB3 sig3.1 sig3.2 256 = true := by decide +kernel
  have h' : mem (2 ^ (256 + 256)) (Real.log 3 / halfWidth) sB3 := by simpa [S512] using h
  have := mem_coarse h' hw
  simpa [RHSingDef0516.σ] using this

theorem w3_mem : mem (2 ^ 256) RHPrSum0511.w3 w3B := by
  have h := RHPrEncl0511.w3_mem
  have hw : within wB3 w3B.1 w3B.2 256 = true := by decide +kernel
  have h' : mem (2 ^ (256 + 256)) RHPrSum0511.w3 wB3 := by simpa [S512] using h
  exact mem_coarse h' hw

theorem kap3_mem : mem (2 ^ 256) ((1 - RHSingDef0516.σ 3 / 2) / (1 + RHSingDef0516.σ 3 / 2)) kap3 :=
  kap_gen hS sig3_mem (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)

lemma logLo3 : ((Llo3 : ℚ) : ℝ) ≤ Real.log ylo3 := by
  have ypos : (0:ℚ) < ylo3 := by decide +kernel
  have e := IntervalRat.mem_logComputable (IntervalRat.mem_singleton ylo3) (by simpa [IntervalRat.singleton] using ypos) 400
  change ((encLo3.lo : ℚ) : ℝ) ≤ Real.log ylo3 ∧ Real.log ylo3 ≤ (encLo3.hi : ℝ) at e
  have f : Llo3 ≤ encLo3.lo := by decide +kernel
  exact le_trans (by exact_mod_cast f) e.1

lemma logHi3 : Real.log yhi3 ≤ ((Lhi3 : ℚ) : ℝ) := by
  have ypos : (0:ℚ) < yhi3 := by decide +kernel
  have e := IntervalRat.mem_logComputable (IntervalRat.mem_singleton yhi3) (by simpa [IntervalRat.singleton] using ypos) 400
  change ((encHi3.lo : ℚ) : ℝ) ≤ Real.log yhi3 ∧ Real.log yhi3 ≤ (encHi3.hi : ℝ) at e
  have f : encHi3.hi ≤ Lhi3 := by decide +kernel
  exact le_trans e.2 (by exact_mod_cast f)

theorem ell3_mem : mem (2 ^ 256) (Real.log (1 - RHSingDef0516.σ 3 / 2) + Real.log (1 + RHSingDef0516.σ 3 / 2)) ell3 :=
  ell_gen hS sig3_mem (ylo := ylo3) (yhi := yhi3) (Llo := Llo3) (Lhi := Lhi3)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    logLo3 logHi3 (by decide +kernel) (by decide +kernel)

/-! ### m = 4 -/

def sig4 : Ball := (199475753779418075501083011590288378482935384050243391385743209945439201569614, 1)
def w4B : Ball := (40130480092995654431116952103154944481626212602261741679307387533530556073300, 289480223093290488558927462521719769633174962)
def kap4 : Ball := (8625022414253784320024322269386310070079938554275951586453081194049563108119, 3)
def ell4 : Ball := (-156842848585876764760004509429630065138568137109896039398982012834795159459698, 6)
def ylo4 : ℚ := (25807080930422121242868511622570041614995216266105156314152569596446987983267389 / 100000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℚ)
def yhi4 : ℚ := (25807080930422121242868511622570041614995216266105156314152569596446987983268877 / 100000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℚ)
def Llo4 : ℚ := (-677260638524394048502352252028209249216002755469323130824621470991641422208143827852128573 / 500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℚ)
def Lhi4 : ℚ := (-677260638524394048502352252028209249216002755469323130824621470991641422208114998555161359 / 500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 : ℚ)
private def encLo4 : IntervalRat := IntervalRat.logComputable (IntervalRat.singleton ylo4) 400
private def encHi4 : IntervalRat := IntervalRat.logComputable (IntervalRat.singleton yhi4) 400

theorem sig4_mem : mem (2 ^ 256) (RHSingDef0516.σ 4) sig4 := by
  have h := RHPrEncl0511.sig4_mem
  have hw : within sB4 sig4.1 sig4.2 256 = true := by decide +kernel
  have h' : mem (2 ^ (256 + 256)) (Real.log 4 / halfWidth) sB4 := by simpa [S512] using h
  have := mem_coarse h' hw
  simpa [RHSingDef0516.σ] using this

theorem w4_mem : mem (2 ^ 256) RHPrSum0511.w4 w4B := by
  have h := RHPrEncl0511.w4_mem
  have hw : within wB4 w4B.1 w4B.2 256 = true := by decide +kernel
  have h' : mem (2 ^ (256 + 256)) RHPrSum0511.w4 wB4 := by simpa [S512] using h
  exact mem_coarse h' hw

theorem kap4_mem : mem (2 ^ 256) ((1 - RHSingDef0516.σ 4 / 2) / (1 + RHSingDef0516.σ 4 / 2)) kap4 :=
  kap_gen hS sig4_mem (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)

lemma logLo4 : ((Llo4 : ℚ) : ℝ) ≤ Real.log ylo4 := by
  have ypos : (0:ℚ) < ylo4 := by decide +kernel
  have e := IntervalRat.mem_logComputable (IntervalRat.mem_singleton ylo4) (by simpa [IntervalRat.singleton] using ypos) 400
  change ((encLo4.lo : ℚ) : ℝ) ≤ Real.log ylo4 ∧ Real.log ylo4 ≤ (encLo4.hi : ℝ) at e
  have f : Llo4 ≤ encLo4.lo := by decide +kernel
  exact le_trans (by exact_mod_cast f) e.1

lemma logHi4 : Real.log yhi4 ≤ ((Lhi4 : ℚ) : ℝ) := by
  have ypos : (0:ℚ) < yhi4 := by decide +kernel
  have e := IntervalRat.mem_logComputable (IntervalRat.mem_singleton yhi4) (by simpa [IntervalRat.singleton] using ypos) 400
  change ((encHi4.lo : ℚ) : ℝ) ≤ Real.log yhi4 ∧ Real.log yhi4 ≤ (encHi4.hi : ℝ) at e
  have f : encHi4.hi ≤ Lhi4 := by decide +kernel
  exact le_trans e.2 (by exact_mod_cast f)

theorem ell4_mem : mem (2 ^ 256) (Real.log (1 - RHSingDef0516.σ 4 / 2) + Real.log (1 + RHSingDef0516.σ 4 / 2)) ell4 :=
  ell_gen hS sig4_mem (ylo := ylo4) (yhi := yhi4) (Llo := Llo4) (Lhi := Lhi4)
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    logLo4 logHi4 (by decide +kernel) (by decide +kernel)

end RHConst0521

