import PolyL0500
import ColDecomp0499

/-! # 0500: certified polynomial approximation of the smooth kernel part `Rk`

`Rk s = exp(s/2)/sinh s − 1/s`. For `0 < s ≤ log 5`, `|Rk s − Q(s/2)| ≤ 2·10⁻²⁴`, where `Q = ql` is
the degree-80 Taylor polynomial of `t ↦ Rk (2t)` (exact rationals, generated by `gen_q.py 80`).

Proof: `Rk(2t) = N/D` with `N = t cosh t + t sinh t − sinh t cosh t`, `D = 2t sinh t cosh t ≥ 2t²`;
`sinh`, `cosh` are replaced by degree-<30 truncations with `Real.exp_bound` errors; the exact
polynomial remainder and the error multipliers are bounded by coefficient absolute sums at
`a = 4024/5000 ≥ log 5 / 2`, checked by `decide +kernel`. No LeanCert; kernel-only decision procedures.
 -/

open Finset
open scoped BigOperators

namespace RHRkApprox0500
open RHPolyL0500

def Sl : List ℚ := (List.range 30).map (fun i => if i % 2 = 1 then 1 / (i.factorial : ℚ) else 0)
def Cl : List ℚ := (List.range 30).map (fun i => if i % 2 = 0 then 1 / (i.factorial : ℚ) else 0)
def ql : List ℚ := [(1/2),
  (-1/12),
  (-1/4),
  (7/720),
  (5/48),
  (-31/30240),
  (-61/1440),
  (127/1209600),
  (277/16128),
  (-73/6842880),
  (-50521/7257600),
  (1414477/1307674368000),
  (540553/191600640),
  (-8191/74724249600),
  (-199360981/174356582400),
  (16931177/1524374691840000),
  (3878302429/8369115955200),
  (-5749691557/5109094217170944000),
  (-2404879675441/12804747411456000),
  (91546277357/802857662698291200000),
  (14814847529501/194632160654131200),
  (-3324754717/287777551824322560000),
  (-69348874393137901/2248001455555215360000),
  (1982765468311237/1693824136731743669452800000),
  (238685140977801337/19090720053330444288000),
  (-22076500342261/186134520519971831808000000),
  (-4087072509293123892361/806582922253211271168000000),
  (65053034220152267/5413323669636552217067520000000),
  (13181680435827682794403/6418701991825554957926400000),
  (-925118910976041358111/759790291646040068357842010112000000),
  (-441543893249023104553682821/530505719624382117272616960000000),
  (16555640865486520478399/134196726836183700385281186201600000000),
  (2088463430347521052196056349/6191313810204553650993364992000000),
  (-8089941578146657681/647203797675420111467194613760000000),
  (-80723299235887898062168247453281/590465598079208281695237219287040000000),
  (29167285342563717499865628061/23029866865868081211368060028922626048000000000),
  (634185543684887724959185841096293/11445948516612345152861521481564160000000),
  (-21194489326041221593005331/165165037094716140555791754978970828800000000),
  (-23489580527043108252017828576198947741/1046045234933202223520014448200148582400000000),
  (20504534628406556573233443388891/1577047683192008049385160068233635435642880000000000),
  (594046028724599200715086271256233067377/65273222659831818747648901567689271541760000000),
  (-3342730069684120811652882591487741/2537441048661701096768915546877587895305109504000000000),
  (-10364622733519612119397957304745185976310201/2810012235505759797086285212489023139872768000000000),
  (22256729848336009246732182756923251/166746126054911786359100164509098633120050053120000000000),
  (1589515884519518540721608102017614123903854761/1063308629915379507217450324405846356127855411200000000),
  (-4204720064739945338027515648494601/310907523355441611672567848311294706434619473920000000000),
  (-350923027193976051443948867093355168290742509719/579223385243377784194768992505289988732805447680000000000),
  (789453341324662409540561918158225679892869/576129822649599132654718834688598335537782181720594841600000000000),
  (5516994249383296071214195242422482492286460673697/22468625506852620218755274293888461608183685709824000000000),
  (-11147697225254007513111810575214137741411/80293206052523318035137285558410989749156973742055751680000000000),
  (-6053285248188621896314383785111649088103498225146815121/60828186403426756087225216332129537688755283137921024000000000000),
  (19824888075038498895325555597751708575618601/1409302181558250186032312226392109774623190259901147381760000000000000),
  (41975241849578121598166907316650470861184801527518616623/1040750647367017788021427572340693767423090392785590681600000000000),
  (-262559530727861921881866927518259047914603716781/184213270476714621616730008661056009704456294528302737023565824000000000000),
  (-175503719511831141815382152695110156842145116853760461828967/10736916155313552580097336868978027027129235561479439122432000000000000),
  (17898125542071873735730356715155014721251666173/123936840591110239052899161148755901877530202690165609909452800000000000000),
  (64967737216691318649670939570279884325581992086894110409620041/9806877073170530370400629620189309651537903156981633912930304000000000000),
  (-59977201118727758119227899690327133403726311223297/4099008429921867066145980878435154867366587490818347759827230392320000000000000),
  (-12622019251806218719903409237287489255482341061191825594069964920041/4701122662565757143658949821030149367657724636362285848841399828480000000000000),
  (700534210387317657846086373720757772905116340448339145899117/472521648504724881947681632159585722781504396170832356365329971241033924608000000000000000),
  (1185526120888983993227221456081974382241144834647221872733754203223/1089490947658447154733399827590620540851610161225695051057188569088000000000000),
  (-914942546207257218347013581951612877187089501496318471/6090962566526697585610281746119502726712054347856432037192871273771827200000000000000),
  (-27757101702071580597366980908371527449233019594800917578033782766889782501/62939946520775875051306244709901528176024561594516464384326336495642214400000000000000),
  (20100142713756778191911006382652359986295781679578907558831/1320659906424508646790837317570048065499212515286082612681407472068561207296000000000000000),
  (28085512897843894225849466174345363694335517968712302712983804234006003567/157135519734841070097131132303605548981876800216155036778702036377974865920000000000000),
  (-159323611326120450488389245384865575324738828109795992797082391/103316988700792580611288457147568559051741746960034723629078513581404257226063872000000000000000),
  (-1292833476501932691491921433154096790811117425770553589060815696637002753202901/17847375051719444721433745581896483693255510307829471296159348421956428890112000000000000000),
  (18481498058322628947716344686182741586483134684345384453338763/118284684058990330664594137610612317061084222640160620303897173514382580876574720000000000000000),
  (29123688760279263001430094018988465332372162571662986597289539553612919097772580417/992014216974732239840396167427668632418959680542147068948684295207288578284873318400000000000000),
  (-77170673236910986782979489874724949419948359134226987131130744239/4874649313545715410889888364727322334263706829003261100174071244780447495002450296832000000000000000),
  (-285051783223697718732198729556739339504255241778255239879353211106980427546235397447421/23957143339939783592145567443378197472917876285092851715110725729256019165579690639360000000000000000),
  (13760869587331995975993746457467711498463585881697886664960973906542546557363/8579000892580528660195091786918216839948295135975948477309820322476390397904697550185671373619200000000000000000),
  (245561214460517407673652820081679655456146784275186259846056537278029024968924948811253/50922626508844978679022095954490372341603402731557030339977559221603646559020115820544000000000000000),
  (-8717850308951125943106241478955633907151863144161504932373403782468541/53641385538152212090695085657500613320921608403394860189828961108445065248806199804202844160000000000000000),
  (-1292973664187864170497603235938698754076170519123672606411370597343787035331808195731850937881/661577088303877282451906056442507564291366503641869942341223853670822471401943130918501744640000000000000000),
  (225913878445347788239012263656524774222058591589057113117183235138438229/13719340540863814613057959695812368844751839937273800647629066089947931434602507323194736640000000000000000000),
  (597385636656915390186148730443428121138584473874136140562762566693379607634403131161792057690569/754197880666420101995172904344458623292157814151731734268995193184737617398215169247091988889600000000000000000),
  (-209664917440381075210488947910949681099079009142171617465640196874495298645923/125665434613005004029351355199575014672013194330240869909640329951736440164304609171910354700075008000000000000000000),
  (-7270601714016864143803280651699281851647234288049207905108309583687335688017641546191095009395592341/22648562356412595662915042317464092457463499158976503980097925651337670650468401532490172426354688000000000000000000),
  (2782816853788582377005851633530926719138614127020726458440267606052697114593813198429/16461690815211137165829600871670134263406127035317546750260943457842801299152989035302284008923260046540800000000000000000000),
  (1068746958875908008291678180949390301975323397102930046690221009795234210820441976633130205853968257/8214571827404740579031452938098884610110147184202668875421457108548297188577348504180079755211571200000000000000000)]

def tl : List ℚ := [0, 1]
def twoT : List ℚ := [0, 2]
def Pl : List ℚ := subL (subL (mulL tl (addL Cl Sl)) (mulL Sl Cl)) (mulL twoT (mulL (mulL Sl Cl) ql))
def A1 : List ℚ := subL (subL tl Cl) (mulL twoT (mulL Cl ql))
def B1 : List ℚ := subL (subL tl Sl) (mulL twoT (mulL Sl ql))
def C1 : List ℚ := addL [1] (mulL twoT ql)
def aQ : ℚ := 4024 / 5000
/-- `31/(30!·30)`, the `Real.exp_bound` constant for `n = 30`. -/
def cE : ℚ := 31 / (265252859812191058636308480000000 * 30)
def EP : ℚ := evQ (absL (Pl.drop 2)) aQ
def EA : ℚ := evQ (absL A1) aQ
def EB : ℚ := evQ (absL B1) aQ
def EC : ℚ := evQ (absL C1) aQ
def bnd : ℚ := (EP + aQ ^ 28 * cE * (EA + EB) + aQ ^ 58 * cE ^ 2 * EC) / 2

lemma Pl_head : Pl.take 2 = [0, 0] := by decide +kernel
lemma bnd_le : bnd ≤ 2 / 10 ^ 24 := by decide +kernel

lemma ev_Sl (t : ℝ) : ev Sl t =
    ((∑ m ∈ range 30, t ^ m / m.factorial) - ∑ m ∈ range 30, (-t) ^ m / m.factorial) / 2 := by
  rw [Sl, ev_range, ← sum_sub_distrib, sum_div]
  refine sum_congr rfl (fun i _ => ?_)
  rcases Nat.even_or_odd i with he | ho
  · have h : i % 2 = 0 := Nat.even_iff.mp he
    simp [h, he.neg_pow]
  · have h : i % 2 = 1 := Nat.odd_iff.mp ho
    simp [h, ho.neg_pow]; ring

lemma ev_Cl (t : ℝ) : ev Cl t =
    ((∑ m ∈ range 30, t ^ m / m.factorial) + ∑ m ∈ range 30, (-t) ^ m / m.factorial) / 2 := by
  rw [Cl, ev_range, ← sum_add_distrib, sum_div]
  refine sum_congr rfl (fun i _ => ?_)
  rcases Nat.even_or_odd i with he | ho
  · have h : i % 2 = 0 := Nat.even_iff.mp he
    simp [h, he.neg_pow]; ring
  · have h : i % 2 = 1 := Nat.odd_iff.mp ho
    simp [h, ho.neg_pow]; ring

lemma exp_pair {t : ℝ} (ht0 : 0 ≤ t) (ht1 : t ≤ 1) :
    |Real.exp t - ∑ m ∈ range 30, t ^ m / m.factorial| ≤ t ^ 30 * cE ∧
    |Real.exp (-t) - ∑ m ∈ range 30, (-t) ^ m / m.factorial| ≤ t ^ 30 * cE := by
  have h1 := Real.exp_bound (x := t) (by rw [abs_of_nonneg ht0]; exact ht1) (n := 30) (by norm_num)
  have h2 := Real.exp_bound (x := -t) (by rw [abs_neg, abs_of_nonneg ht0]; exact ht1) (n := 30)
    (by norm_num)
  rw [abs_of_nonneg ht0] at h1
  rw [abs_neg, abs_of_nonneg ht0] at h2
  have hc : ((Nat.succ 30 : ℕ) : ℝ) / ((Nat.factorial 30 : ℕ) * (30 : ℕ)) = (cE : ℝ) := by
    rw [cE, Nat.factorial]; norm_num [Nat.factorial]
  rw [hc] at h1 h2
  exact ⟨h1, h2⟩

lemma sinh_near {t : ℝ} (ht0 : 0 ≤ t) (ht1 : t ≤ 1) : |Real.sinh t - ev Sl t| ≤ t ^ 30 * cE := by
  obtain ⟨h1, h2⟩ := exp_pair ht0 ht1
  rw [ev_Sl, Real.sinh_eq]
  have : Real.exp t - Real.exp (-t) - ((∑ m ∈ range 30, t ^ m / m.factorial) -
      ∑ m ∈ range 30, (-t) ^ m / m.factorial) =
      (Real.exp t - ∑ m ∈ range 30, t ^ m / m.factorial) -
      (Real.exp (-t) - ∑ m ∈ range 30, (-t) ^ m / m.factorial) := by ring
  rw [← sub_div, this, abs_div, abs_two]
  have := abs_sub (Real.exp t - ∑ m ∈ range 30, t ^ m / m.factorial)
    (Real.exp (-t) - ∑ m ∈ range 30, (-t) ^ m / m.factorial)
  rw [div_le_iff₀ (by norm_num)]; linarith

lemma cosh_near {t : ℝ} (ht0 : 0 ≤ t) (ht1 : t ≤ 1) : |Real.cosh t - ev Cl t| ≤ t ^ 30 * cE := by
  obtain ⟨h1, h2⟩ := exp_pair ht0 ht1
  rw [ev_Cl, Real.cosh_eq]
  have : Real.exp t + Real.exp (-t) - ((∑ m ∈ range 30, t ^ m / m.factorial) +
      ∑ m ∈ range 30, (-t) ^ m / m.factorial) =
      (Real.exp t - ∑ m ∈ range 30, t ^ m / m.factorial) +
      (Real.exp (-t) - ∑ m ∈ range 30, (-t) ^ m / m.factorial) := by ring
  rw [← sub_div, this, abs_div, abs_two]
  have := abs_add_le (Real.exp t - ∑ m ∈ range 30, t ^ m / m.factorial)
    (Real.exp (-t) - ∑ m ∈ range 30, (-t) ^ m / m.factorial)
  rw [div_le_iff₀ (by norm_num)]; linarith

lemma Rk_two_mul {t : ℝ} (ht : 0 < t) :
    RHColDecomp0499.Rk (2 * t) =
      (t * Real.cosh t + t * Real.sinh t - Real.sinh t * Real.cosh t) /
        (2 * t * Real.sinh t * Real.cosh t) := by
  have hsh : 0 < Real.sinh t := Real.sinh_pos_iff.mpr ht
  have hch : 0 < Real.cosh t := Real.cosh_pos t
  unfold RHColDecomp0499.Rk RH_GammaFinalFormula.K_kernel RH_GammaSqrtBound.K_kernel
  rw [show 2 * t / 2 = t by ring, Real.sinh_two_mul, ← Real.cosh_add_sinh]
  field_simp

theorem Rk_two_mul_approx {t : ℝ} (ht : 0 < t) (hta : t ≤ aQ) :
    |RHColDecomp0499.Rk (2 * t) - ev ql t| ≤ (bnd : ℝ) := by
  have ha1 : ((aQ : ℚ) : ℝ) ≤ 1 := by unfold aQ; norm_num
  have ht1 : t ≤ 1 := hta.trans ha1
  have hsh : t ≤ Real.sinh t := Real.self_le_sinh_iff.mpr ht.le
  have hch : 1 ≤ Real.cosh t := Real.one_le_cosh t
  have hshp : 0 < Real.sinh t := ht.trans_le hsh
  have hD : 0 < 2 * t * Real.sinh t * Real.cosh t := by positivity
  set sh := Real.sinh t with hsh_def
  set ch := Real.cosh t with hch_def
  set S := ev Sl t
  set C := ev Cl t
  set Q := ev ql t
  have hP : ev Pl t = t * (C + S) - S * C - 2 * t * (S * C * Q) := by
    simp only [Pl, ev_subL, ev_mulL, ev_addL, tl, twoT, ev]; push_cast; ring
  have hA : ev A1 t = t - C - 2 * t * (C * Q) := by
    simp only [A1, ev_subL, ev_mulL, tl, twoT, ev]; push_cast; ring
  have hB : ev B1 t = t - S - 2 * t * (S * Q) := by
    simp only [B1, ev_subL, ev_mulL, tl, twoT, ev]; push_cast; ring
  have hC : ev C1 t = 1 + 2 * t * Q := by
    simp only [C1, ev_addL, ev_mulL, twoT, ev]; push_cast; ring
  set a := sh - S with ha_def
  set b := ch - C with hb_def
  have hdiff : RHColDecomp0499.Rk (2 * t) - Q =
      (ev Pl t + a * ev A1 t + b * ev B1 t + -(a * b * ev C1 t)) / (2 * t * sh * ch) := by
    rw [Rk_two_mul ht, hP, hA, hB, hC, ha_def, hb_def]
    field_simp
    ring
  have hta' : t ≤ ((aQ : ℚ) : ℝ) := hta
  have hEPn : 0 ≤ ((EP : ℚ) : ℝ) := by rw [EP, ← ev_cast]; exact ev_absL_nonneg _ (by unfold aQ; norm_num)
  have hEAn : 0 ≤ ((EA : ℚ) : ℝ) := by rw [EA, ← ev_cast]; exact ev_absL_nonneg _ (by unfold aQ; norm_num)
  have hEBn : 0 ≤ ((EB : ℚ) : ℝ) := by rw [EB, ← ev_cast]; exact ev_absL_nonneg _ (by unfold aQ; norm_num)
  have hECn : 0 ≤ ((EC : ℚ) : ℝ) := by rw [EC, ← ev_cast]; exact ev_absL_nonneg _ (by unfold aQ; norm_num)
  have hcE : (0 : ℝ) ≤ (cE : ℝ) := by unfold cE; norm_num
  have hPb : |ev Pl t| ≤ t ^ 2 * (EP : ℝ) := by
    rw [ev_drop_two Pl_head, abs_mul, abs_of_nonneg (sq_nonneg t)]
    exact mul_le_mul_of_nonneg_left (abs_ev_le_evQ _ aQ ht.le hta) (sq_nonneg t)
  have hAb : |ev A1 t| ≤ (EA : ℝ) := abs_ev_le_evQ _ aQ ht.le hta
  have hBb : |ev B1 t| ≤ (EB : ℝ) := abs_ev_le_evQ _ aQ ht.le hta
  have hCb : |ev C1 t| ≤ (EC : ℝ) := abs_ev_le_evQ _ aQ ht.le hta
  have hab : |a| ≤ t ^ 30 * cE := sinh_near ht.le ht1
  have hbb : |b| ≤ t ^ 30 * cE := cosh_near ht.le ht1
  have h30 : 0 ≤ t ^ 30 * (cE : ℝ) := by positivity
  have t1 : |a * ev A1 t| ≤ t ^ 30 * cE * EA := by
    rw [abs_mul]; exact mul_le_mul hab hAb (abs_nonneg _) h30
  have t2 : |b * ev B1 t| ≤ t ^ 30 * cE * EB := by
    rw [abs_mul]; exact mul_le_mul hbb hBb (abs_nonneg _) h30
  have t3 : |-(a * b * ev C1 t)| ≤ t ^ 30 * cE * (t ^ 30 * cE) * EC := by
    rw [abs_neg, abs_mul, abs_mul]
    exact mul_le_mul (mul_le_mul hab hbb (abs_nonneg _) h30) hCb (abs_nonneg _) (by positivity)
  have hnum : |ev Pl t + a * ev A1 t + b * ev B1 t + -(a * b * ev C1 t)| ≤
      t ^ 2 * ((EP : ℝ) + t ^ 28 * cE * (EA + EB) + t ^ 58 * cE ^ 2 * EC) := by
    have e1 := abs_add_le (ev Pl t + a * ev A1 t + b * ev B1 t) (-(a * b * ev C1 t))
    have e2 := abs_add_le (ev Pl t + a * ev A1 t) (b * ev B1 t)
    have e3 := abs_add_le (ev Pl t) (a * ev A1 t)
    have : t ^ 2 * ((EP : ℝ) + t ^ 28 * cE * (EA + EB) + t ^ 58 * cE ^ 2 * EC) =
        t ^ 2 * EP + t ^ 30 * cE * EA + t ^ 30 * cE * EB + t ^ 30 * cE * (t ^ 30 * cE) * EC := by ring
    rw [this]; linarith
  have hX : (EP : ℝ) + t ^ 28 * cE * (EA + EB) + t ^ 58 * cE ^ 2 * EC ≤ 2 * (bnd : ℝ) := by
    have p28 : t ^ 28 ≤ ((aQ : ℚ) : ℝ) ^ 28 := pow_le_pow_left₀ ht.le hta' 28
    have p58 : t ^ 58 ≤ ((aQ : ℚ) : ℝ) ^ 58 := pow_le_pow_left₀ ht.le hta' 58
    have q1 : t ^ 28 * cE * (EA + EB) ≤ ((aQ : ℚ) : ℝ) ^ 28 * cE * (EA + EB) := by
      apply mul_le_mul_of_nonneg_right (mul_le_mul_of_nonneg_right p28 hcE); positivity
    have q2 : t ^ 58 * cE ^ 2 * EC ≤ ((aQ : ℚ) : ℝ) ^ 58 * cE ^ 2 * EC := by
      apply mul_le_mul_of_nonneg_right (mul_le_mul_of_nonneg_right p58 (by positivity)) hECn
    have : 2 * (bnd : ℝ) = (EP : ℝ) + ((aQ : ℚ) : ℝ) ^ 28 * cE * (EA + EB) +
        ((aQ : ℚ) : ℝ) ^ 58 * cE ^ 2 * EC := by
      rw [bnd]; push_cast; ring
    rw [this]; linarith
  have hbndn : 0 ≤ (bnd : ℝ) := by
    have : 0 ≤ (EP : ℝ) + t ^ 28 * cE * (EA + EB) + t ^ 58 * cE ^ 2 * EC := by positivity
    linarith
  have hDl : 2 * t ^ 2 ≤ 2 * t * sh * ch := by
    have : t * 1 ≤ sh * ch := mul_le_mul hsh hch zero_le_one hshp.le
    nlinarith
  rw [hdiff, abs_div, abs_of_pos hD, div_le_iff₀ hD]
  calc _ ≤ t ^ 2 * ((EP : ℝ) + t ^ 28 * cE * (EA + EB) + t ^ 58 * cE ^ 2 * EC) := hnum
    _ ≤ t ^ 2 * (2 * (bnd : ℝ)) := mul_le_mul_of_nonneg_left hX (sq_nonneg t)
    _ = (bnd : ℝ) * (2 * t ^ 2) := by ring
    _ ≤ (bnd : ℝ) * (2 * t * sh * ch) := mul_le_mul_of_nonneg_left hDl hbndn

/-- Main result: `|Rk s − Q(s/2)| ≤ 2·10⁻²⁴` on `(0, log 5]`. -/
theorem Rk_approx {s : ℝ} (hs : 0 < s) (hs5 : s ≤ Real.log 5) :
    |RHColDecomp0499.Rk s - ev ql (s / 2)| ≤ 2 / 10 ^ 24 := by
  have h5 := RHEntry00Bounds0495.b_l5.2
  have hq : (RHEntry00Bounds0495.l5H : ℝ) ≤ 2 * ((aQ : ℚ) : ℝ) := by
    have : RHEntry00Bounds0495.l5H ≤ 2 * aQ := by decide +kernel
    exact_mod_cast this
  have h := Rk_two_mul_approx (t := s / 2) (by positivity) (by linarith)
  rw [show 2 * (s / 2) = s by ring] at h
  have hb := (Rat.cast_le (K := ℝ)).mpr bnd_le
  push_cast at hb
  linarith

end RHRkApprox0500

