# Generate <trial>/MathlibAll0483.lean: all imports of pinned Mathlib 5ed2965 Mathlib.lean, as plain `import`,
# except Mathlib.Probability.Kernel.Invariance (its olean is absent from the shared leancert_0455 cache, which we may not write).
import re,hashlib,json
from pathlib import Path
orig=Path('<DEV>/tool_trials/leancert_0455/.lake/packages/mathlib/Mathlib.lean')
lines=orig.read_text().splitlines()
imps=[m.group(1) for l in lines if (m:=re.match(r'^public import (\S+)\s*$',l))]
excluded=['Mathlib.Probability.Kernel.Invariance']
kept=[i for i in imps if i not in excluded]
body='-- 0483: Mathlib umbrella minus modules missing from the shared cache. Generated by gen_umbrella.py.\n'+''.join(f'import {i}\n' for i in kept)
out=Path('<DEV>/tool_trials/rh_main_0481/MathlibAll0483.lean');out.write_text(body)
info=dict(orig=str(orig),orig_sha=hashlib.sha256(orig.read_bytes()).hexdigest(),orig_import_count=len(imps),excluded=excluded,kept_count=len(kept),out=str(out),out_sha=hashlib.sha256(out.read_bytes()).hexdigest())
Path('umbrella.json').write_text(json.dumps(info,indent=1)+'\n');print(info)
