# 0521: M^κ tables (w = log(1+κ t)), base = RHLamDef0521.lamBase (2^256) kap_m 170 127, rows j<64
import re
from gen_lam import lamBase
from gen_tab import rows, lean_row_defs
import mpmath as mp
S=2**256; mp.mp.dps=80
src0=open('Const0521.lean').read()
for m in (2,3,4):
  mm=re.search(r'def kap%d : Ball := \((-?\d+), (\d+)\)'%m,src0); kB=(int(mm.group(1)),int(mm.group(2)))
  base=lamBase(S,kB,170,127); t=rows(base,64)
  k=mp.mpf(kB[0])/S
  for (j,l) in [(0,0),(5,7),(63,63)]:
    q=mp.quad(lambda u: mp.log(1+k*u)*mp.legendre(j,u)*mp.legendre(l,u),[-1,0,1])
    print(m,j,l,mp.nstr(mp.mpf(t[j][l][0])/S-q,4),'rad',mp.nstr(mp.mpf(t[j][l][1])/S,4))
  src=f'''import TabCore0515
import Const0521

/-! # 0521: kernel-checked table of `Mκ(j,l) = ∫ log(1+κt) P_j P_l`, κ = (1−σ_{m}/2)/(1+σ_{m}/2) (m = {m}),
j < 64, l < 127 − j, scale `2^256`; base row `lamBase (2^256) kap{m} 170 127`. Generated by `gen_mk.py`.
Candidate only. -/

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace RHMkTab{m}_0521
open RHBall0504 RHBallVec0504 RHRec2D0515 RHTabCore0515

{lean_row_defs(t)}

theorem tab_base : tab.getD 0 [] = RHLamDef0521.lamBase (2 ^ 256) RHConst0521.kap{m} 170 127 := by decide +kernel
theorem tab_chk1 : chk1 tab = true := by decide +kernel
theorem tab_chk : chkFrom 0 tab = true := by decide +kernel

end RHMkTab{m}_0521
'''
  open(f'MkTabData{m}_0521.lean','w').write(src); print('bytes',len(src))
