# 0521: generate Const0521.lean (σ, w at 2^256; κ and ℓ = log(1-σ/2)+log(1+σ/2) balls with proofs)
import re, math
from fractions import Fraction as Fr
import mpmath as mp
from ballops import coarse, ball_of_bounds
mp.mp.dps=120
TR='<DEV>/tool_trials/rh_trunc_0500/'
def lean_ball(name):
  t=open(TR+'PrEncl0511.lean').read(); m=re.search(r'def '+name+r' : Ball := \((-?\d+), (\d+)\)',t); return (int(m.group(1)),int(m.group(2)))
S=2**256; D=10**80
out=[]
for m in (2,3,4):
  sB=lean_ball('sB%d'%m); wB=lean_ball('wB%d'%m)
  sc=coarse(sB,256); wc=coarse(wB,256)
  lo=Fr(sc[0]-sc[1],S); hi=Fr(sc[0]+sc[1],S)
  klo=(2-hi)/(2+hi); khi=(2-lo)/(2+lo)
  kB=ball_of_bounds(S,klo,khi)
  ylo=Fr(math.floor((1-hi*hi/4)*D),D); yhi=Fr(math.ceil((1-lo*lo/4)*D),D)
  Llo=Fr(int(mp.floor(mp.log(mp.mpf(ylo.numerator)/ylo.denominator)*10**90))-2,10**90)
  Lhi=Fr(int(mp.ceil(mp.log(mp.mpf(yhi.numerator)/yhi.denominator)*10**90))+2,10**90)
  lB=ball_of_bounds(S,Llo,Lhi)
  out.append(dict(m=m,sc=sc,wc=wc,kB=kB,ylo=ylo,yhi=yhi,Llo=Llo,Lhi=Lhi,lB=lB))
def q(x): return f'({x.numerator} / {x.denominator} : ℚ)'
src='''import LamDef0521
import PrEncl0511
import FRed0516
import Coarse0509
import LeanCert.Core.IntervalRat.Taylor

/-! # 0521: constant balls at scale `2^256` for the G6c pipeline (generated by `gen_const.py`)

For `m = 2, 3, 4` (`σ = σ m = log m / L`): `σ`, `w_m`, `κ = (1−σ/2)/(1+σ/2)`,
`ℓ = log(1−σ/2) + log(1+σ/2)`. LeanCert `logComputable` for the rational log bounds. Candidate only. -/

set_option maxRecDepth 100000
set_option maxHeartbeats 10000000

open LeanCert.Core

namespace RHConst0521
open RHBall0504 RHCoarse0509 RHPrEncl0511 RHBallMisc0512 RHLog5Bridge

lemma hS : 0 < (2:ℕ) ^ 256 := by positivity

lemma mem_bounds {S : ℕ} (hS : 0 < S) {x : ℝ} {b : Ball} (h : mem S x b) :
    ((b.1 : ℝ) - b.2) / S ≤ x ∧ x ≤ ((b.1 : ℝ) + b.2) / S := by
  unfold mem at h
  have hS' : (0:ℝ) < S := by exact_mod_cast hS
  rw [abs_le] at h
  constructor
  · rw [sub_div]; linarith [h.2]
  · rw [add_div]; linarith [h.1]

lemma kappa_bounds {σ lo hi : ℝ} (h1 : lo ≤ σ) (h2 : σ ≤ hi) (h0 : 0 ≤ lo) (h3 : hi < 2) :
    (2 - hi) / (2 + hi) ≤ (1 - σ / 2) / (1 + σ / 2) ∧ (1 - σ / 2) / (1 + σ / 2) ≤ (2 - lo) / (2 + lo) := by
  have e : (1 - σ / 2) / (1 + σ / 2) = (2 - σ) / (2 + σ) := by field_simp
  rw [e]
  constructor
  · rw [div_le_div_iff₀ (by linarith) (by linarith)]; nlinarith
  · rw [div_le_div_iff₀ (by linarith) (by linarith)]; nlinarith

lemma ell_eq {σ : ℝ} (h0 : 0 ≤ σ) (h2 : σ < 2) :
    Real.log (1 - σ / 2) + Real.log (1 + σ / 2) = Real.log (1 - σ ^ 2 / 4) := by
  rw [← Real.log_mul (by linarith) (by linarith)]; congr 1; ring

theorem kap_gen {S : ℕ} (hS : 0 < S) {σ : ℝ} {sB kB : Ball} (hσ : mem S σ sB)
    (c0 : (0 : ℚ) ≤ ((sB.1 : ℚ) - sB.2) / S) (c3 : ((sB.1 : ℚ) + sB.2) / S < 2)
    (c1 : ((kB.1 : ℚ) - kB.2) / S ≤ (2 - ((sB.1 : ℚ) + sB.2) / S) / (2 + ((sB.1 : ℚ) + sB.2) / S))
    (c2 : (2 - ((sB.1 : ℚ) - sB.2) / S) / (2 + ((sB.1 : ℚ) - sB.2) / S) ≤ ((kB.1 : ℚ) + kB.2) / S) :
    mem S ((1 - σ / 2) / (1 + σ / 2)) kB := by
  obtain ⟨h1, h2⟩ := mem_bounds hS hσ
  have r0 : (0:ℝ) ≤ ((sB.1 : ℝ) - sB.2) / S := by exact_mod_cast c0
  have r3 : ((sB.1 : ℝ) + sB.2) / S < 2 := by exact_mod_cast c3
  have d1 : ((kB.1 : ℝ) - kB.2) / S ≤ (2 - ((sB.1 : ℝ) + sB.2) / S) / (2 + ((sB.1 : ℝ) + sB.2) / S) := by
    exact_mod_cast c1
  have d2 : (2 - ((sB.1 : ℝ) - sB.2) / S) / (2 + ((sB.1 : ℝ) - sB.2) / S) ≤ ((kB.1 : ℝ) + kB.2) / S := by
    exact_mod_cast c2
  obtain ⟨k1, k2⟩ := kappa_bounds h1 h2 r0 r3
  exact mem_of_bounds' hS (by linarith) (by linarith)

theorem ell_gen {S : ℕ} (hS : 0 < S) {σ : ℝ} {sB lB : Ball} (hσ : mem S σ sB) {ylo yhi Llo Lhi : ℚ}
    (c0 : (0 : ℚ) ≤ ((sB.1 : ℚ) - sB.2) / S) (c3 : ((sB.1 : ℚ) + sB.2) / S < 2)
    (cy1 : ylo ≤ 1 - (((sB.1 : ℚ) + sB.2) / S) ^ 2 / 4) (cy2 : 1 - (((sB.1 : ℚ) - sB.2) / S) ^ 2 / 4 ≤ yhi)
    (ypos : 0 < ylo) (hlo : (Llo : ℝ) ≤ Real.log ylo) (hhi : Real.log yhi ≤ Lhi)
    (c1 : ((lB.1 : ℚ) - lB.2) / S ≤ Llo) (c2 : Lhi ≤ ((lB.1 : ℚ) + lB.2) / S) :
    mem S (Real.log (1 - σ / 2) + Real.log (1 + σ / 2)) lB := by
  obtain ⟨h1, h2⟩ := mem_bounds hS hσ
  have r0 : (0:ℝ) ≤ ((sB.1 : ℝ) - sB.2) / S := by exact_mod_cast c0
  have r3 : ((sB.1 : ℝ) + sB.2) / S < 2 := by exact_mod_cast c3
  have hσ0 : 0 ≤ σ := le_trans r0 h1
  have hσ2 : σ < 2 := lt_of_le_of_lt h2 r3
  rw [ell_eq hσ0 hσ2]
  have dy1 : (ylo : ℝ) ≤ 1 - (((sB.1 : ℝ) + sB.2) / S) ^ 2 / 4 := by exact_mod_cast cy1
  have dy2 : 1 - (((sB.1 : ℝ) - sB.2) / S) ^ 2 / 4 ≤ (yhi : ℝ) := by exact_mod_cast cy2
  have sq1 : σ ^ 2 ≤ (((sB.1 : ℝ) + sB.2) / S) ^ 2 := pow_le_pow_left₀ hσ0 h2 2
  have sq2 : (((sB.1 : ℝ) - sB.2) / S) ^ 2 ≤ σ ^ 2 := pow_le_pow_left₀ r0 h1 2
  have ypos' : (0:ℝ) < ylo := by exact_mod_cast ypos
  have l1 := Real.log_le_log ypos' (show (ylo : ℝ) ≤ 1 - σ ^ 2 / 4 by linarith)
  have l2 := Real.log_le_log (by nlinarith) (show 1 - σ ^ 2 / 4 ≤ (yhi : ℝ) by linarith)
  have d1 : ((lB.1 : ℝ) - lB.2) / S ≤ Llo := by exact_mod_cast c1
  have d2 : (Lhi : ℝ) ≤ ((lB.1 : ℝ) + lB.2) / S := by exact_mod_cast c2
  exact mem_of_bounds' hS (by linarith) (by linarith)

'''
for d in out:
  m=d['m']
  src+=f'''/-! ### m = {m} -/

def sig{m} : Ball := ({d['sc'][0]}, {d['sc'][1]})
def w{m}B : Ball := ({d['wc'][0]}, {d['wc'][1]})
def kap{m} : Ball := ({d['kB'][0]}, {d['kB'][1]})
def ell{m} : Ball := ({d['lB'][0]}, {d['lB'][1]})
def ylo{m} : ℚ := {q(d['ylo'])}
def yhi{m} : ℚ := {q(d['yhi'])}
def Llo{m} : ℚ := {q(d['Llo'])}
def Lhi{m} : ℚ := {q(d['Lhi'])}
private def encLo{m} : IntervalRat := IntervalRat.logComputable (IntervalRat.singleton ylo{m}) 400
private def encHi{m} : IntervalRat := IntervalRat.logComputable (IntervalRat.singleton yhi{m}) 400

theorem sig{m}_mem : mem (2 ^ 256) (RHSingDef0516.σ {m}) sig{m} := by
  have h := RHPrEncl0511.sig{m}_mem
  have hw : within sB{m} sig{m}.1 sig{m}.2 256 = true := by decide +kernel
  have h' : mem (2 ^ (256 + 256)) (Real.log {m} / halfWidth) sB{m} := by simpa [S512] using h
  have := mem_coarse h' hw
  simpa [RHSingDef0516.σ] using this

theorem w{m}_mem : mem (2 ^ 256) RHPrSum0511.w{m} w{m}B := by
  have h := RHPrEncl0511.w{m}_mem
  have hw : within wB{m} w{m}B.1 w{m}B.2 256 = true := by decide +kernel
  have h' : mem (2 ^ (256 + 256)) RHPrSum0511.w{m} wB{m} := by simpa [S512] using h
  exact mem_coarse h' hw

theorem kap{m}_mem : mem (2 ^ 256) ((1 - RHSingDef0516.σ {m} / 2) / (1 + RHSingDef0516.σ {m} / 2)) kap{m} :=
  kap_gen hS sig{m}_mem (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)

lemma logLo{m} : ((Llo{m} : ℚ) : ℝ) ≤ Real.log ylo{m} := by
  have ypos : (0:ℚ) < ylo{m} := by decide +kernel
  have e := IntervalRat.mem_logComputable (IntervalRat.mem_singleton ylo{m}) (by simpa [IntervalRat.singleton] using ypos) 400
  change ((encLo{m}.lo : ℚ) : ℝ) ≤ Real.log ylo{m} ∧ Real.log ylo{m} ≤ (encLo{m}.hi : ℝ) at e
  have f : Llo{m} ≤ encLo{m}.lo := by decide +kernel
  exact le_trans (by exact_mod_cast f) e.1

lemma logHi{m} : Real.log yhi{m} ≤ ((Lhi{m} : ℚ) : ℝ) := by
  have ypos : (0:ℚ) < yhi{m} := by decide +kernel
  have e := IntervalRat.mem_logComputable (IntervalRat.mem_singleton yhi{m}) (by simpa [IntervalRat.singleton] using ypos) 400
  change ((encHi{m}.lo : ℚ) : ℝ) ≤ Real.log yhi{m} ∧ Real.log yhi{m} ≤ (encHi{m}.hi : ℝ) at e
  have f : encHi{m}.hi ≤ Lhi{m} := by decide +kernel
  exact le_trans e.2 (by exact_mod_cast f)

theorem ell{m}_mem : mem (2 ^ 256) (Real.log (1 - RHSingDef0516.σ {m} / 2) + Real.log (1 + RHSingDef0516.σ {m} / 2)) ell{m} :=
  ell_gen hS sig{m}_mem (ylo := ylo{m}) (yhi := yhi{m}) (Llo := Llo{m}) (Lhi := Lhi{m})
    (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)
    logLo{m} logHi{m} (by decide +kernel) (by decide +kernel)

'''
src+='end RHConst0521\n\n'+''.join(f'#print axioms RHConst0521.{n}{m}_mem\n' for m in (2,3,4) for n in ('sig','w','kap','ell'))
open('Const0521.lean','w').write(src)
print(len(src))
